upstream django {
    server unix:/run/batchit.sock;
}

server {
    listen 80;
    server_name example.com; # change to your domain or VPS IP

    # Serve static files
    location /static/ {
        alias /path/to/BatchIt-Backend/static/; # change to your STATIC_ROOT
    }

    location / {
        include proxy_params;
        proxy_pass http://django;
    }

    access_log /var/log/nginx/batchit_access.log;
    error_log /var/log/nginx/batchit_error.log;
}
